cake-contrib/Cake.7zip

src/Cake.7zip/Cake.7zip.csproj

removed symbol-generation and embedded pdb

---

.github/workflows/publishDocs.yml
src/.editorconfig
src/Cake.7zip.Tests/Cake.7zip.Tests.csproj
src/Cake.7zip/Cake.7zip.csproj
src/Directory.Build.props
src/cake.7zip.ruleset

added <LangVersion>7.3</LangVersion>

---

.appveyor.yml
src/Cake.7zip/Cake.7zip.csproj

and added PackageIconUrl for compatibility

switched appveyor image to vs 2019

---

src/Cake.7zip.Tests/Commands/BenchmarkCommandTests.cs
src/Cake.7zip.Tests/Commands/CommandExtensionTests.cs
src/Cake.7zip.Tests/Fixtures/Outputs.cs
src/Cake.7zip.Tests/FluentBuilder/BenchmarkCommandBuilderTests.cs
src/Cake.7zip.Tests/Parsers/BenchmarkOutputParserTests.cs
src/Cake.7zip/Builder/BenchmarkCommandBuilder.cs
src/Cake.7zip/Builder/CommandBuilder.cs
src/Cake.7zip/Commands/BenchmarkCommand.cs
src/Cake.7zip/Parsers/BenchmarkOutputParser.cs
src/Cake.7zip/Parsers/IBenchmarkOutput.cs

(GH-28) Implemented command: b (Benchmark)

---

demo/.gitignore
demo/build.cake
demo/build.ps1
demo/build.sh
src/Cake.7zip.Tests/Commands/GeneralOutputCommandTests.cs
src/Cake.7zip.Tests/Fixtures/Outputs.cs
src/Cake.7zip.Tests/FluentBuilder/GeneralCommandBuilderTests.cs
src/Cake.7zip.Tests/FluentBuilder/InformationCommandBuilderTests.cs
src/Cake.7zip.Tests/FluentBuilder/ListCommandBuilderTests.cs
src/Cake.7zip.Tests/FluentBuilder/SwitchShowTechnicalInformationBuilderTests.cs
src/Cake.7zip.Tests/Parsers/ListOutputParserTests.cs
src/Cake.7zip.Tests/Settings/Switches/SwitchShowTechnicalInformationTests.cs
src/Cake.7zip/Builder/AddCommandBuilder.cs
src/Cake.7zip/Builder/CommandBuilder.cs
src/Cake.7zip/Builder/DeleteCommandBuilder.cs
src/Cake.7zip/Builder/HashCommandBuilder.cs
src/Cake.7zip/Builder/InformationCommandBuilder.cs
src/Cake.7zip/Builder/ListCommandBuilder.cs
src/Cake.7zip/Builder/SwitchShowTechnicalInformationBuilder.cs
src/Cake.7zip/Builder/TestCommandBuilder.cs
src/Cake.7zip/Builder/UpdateCommandBuilder.cs
src/Cake.7zip/Commands/ListCommand.cs
src/Cake.7zip/Parsers/IArchiveListOutput.cs
src/Cake.7zip/Parsers/IArchivedFileListOutput.cs
src/Cake.7zip/Parsers/IListOutput.cs
src/Cake.7zip/Parsers/ListOutputParser.cs
src/Cake.7zip/SevenZipAliases.cs
src/Cake.7zip/Switches/ISupportSwitchShowTechnicalInformation.cs
src/Cake.7zip/Switches/SwitchShowTechnicalInformation.cs
src/vsspell.ignoredWords.txt

Implemented command l and fixed broken examples

---

.github/workflows/publishDocs.yml
demo/build.cake
src/Cake.7zip.Tests/FluentBuilder/RenameCommandBuilderTests.cs
src/Cake.7zip/Arguments/RenamePair.cs
src/Cake.7zip/Builder/CommandBuilder.cs
src/Cake.7zip/Builder/RenameCommandBuilder.cs
src/Cake.7zip/Commands/ListCommand.cs
src/Cake.7zip/Commands/RenameCommand.cs
src/vsspell.ignoredWords.txt

(GH-32) implemented command: rn

---

src/Cake.7zip/Cake.7zip.csproj

(GH-59) added references to Cake.Addin.Analyzer and CakeContrib.Guidelines

---

recipe.cake
src/Cake.7zip/Cake.7zip.csproj
src/stylecop.json

Bumped CakeContrib.Guidelines to 0.4.0

(maint) Bumped Cake.Recipe to stable 2.0.0 version

---

demo/build.cake
src/Cake.7zip.Tests/Settings/Switches/SwitchArchiveTypeTests.cs
src/Cake.7zip/Builder/ExtractCommandBuilder.cs
src/Cake.7zip/Switches/SwitchArchiveType.cs

to use e/x/t/l with volume-archives.
This relates to #78

(GH-78) added SwitchArchiveType.Volumes()

---

.github/workflows/dependabot-cake.yml

this will run dependabot-cake to check for updated references in cake-files

added dependabot-cake action

---

README.md
src/Cake.7zip/Cake.7zip.csproj

Fixes casing in NuGet package description

Fix casing in package description

---

.gitignore
src/Cake.7zip/Cake.7zip.csproj

and replaced with Microsoft.CodeAnalysis.NetAnalyzers
fixes #100

(GH-100) removed FxCopAnalyzers

---

src/Cake.7zip/Commands/ListCommand.cs
src/Cake.7zip/Namespaces.cs

(GH-108) added documentation for Namespaces

---

src/Cake.7zip.Tests/Cake.7zip.Tests.csproj
src/Cake.7zip/Cake.7zip.csproj

(GH-111) bumped Cake references to Cake 1.0.0

---

.github/workflows/build.yml
.github/workflows/codeql-analysis.yml

(GH-125) updated gh-builds to best practices

---

src/Cake.7zip/Cake.7zip.csproj

(GH-126) updated NuGet Tags

---

GitReleaseManager.yaml

(GH-129) updated GRM config

---

GitReleaseManager.yaml

(GH-131) fixed NuGet link in GRM config

---

src/.idea/.idea.Cake.7zip/.idea/riderModule.iml
src/Cake.7zip/Cake.7zip.csproj

(GH-134) updated CCG

---

.github/workflows/codeql-analysis.yml
.github/workflows/publishDocs.yml

(GH-136) fixed codeql-analysis

---

src/Cake.7zip/Cake.7zip.csproj

this will also update the logo and fix #139

(GH-139) updated CakeContrib.Guidelines

---

docs/input/_Bottom.cshtml
docs/input/assets/css/override.less

This PR fixes #158 
Added the buttons and some CSS

Issue #158: addes GitHub-Buttons and according CSS

---

.azure-pipelines.yaml
.config/dotnet-tools.json
.gitpod.Dockerfile
.gitpod.yml
build.ps1
build.sh

So working on GitPod is seamlessly possible.
Also bumped Cake to 0.38.5 and updated bootstrappers.

(maint) added GitPod settings

---

.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
demo/cake/.config/dotnet-tools.json
demo/cake/build.cake
demo/frosting/build/Build.csproj
src/Cake.7zip.Tests/Cake.7zip.Tests.csproj
src/Cake.7zip/Cake.7zip.csproj

and CakeContrib.Guidelines to 1.3.0

(#173) bumped Cake to 2.0.0

---

.config/dotnet-tools.json
.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.github/workflows/publishDocs.yml
build.ps1
build.sh
recipe.cake

according to https://cake-contrib.github.io/Cake.Recipe/docs/upgrading/2.x-to-3.x

(maint) pinned to Cake 1.3.0 and bumped to Cake.Recipe 3

---

.github/workflows/codeql-analysis.yml

(#242) add .NET 5 to codeql workflow

---

src/Cake.7zip.Tests/Cake.7zip.Tests.csproj
src/Cake.7zip/Cake.7zip.csproj

and CakeContrib.Guidelines to 1.5.1
fixes #284

(#284) Update Cake.Core to 4.0.0

---

.github/workflows/build.yml

(#387) switched runner from macos-12 to macos-13
